package Logic;

public enum Tilstand {

	VAEGT, PROFIL, VINKEL, TYNGDEKRAFT, DIMENSIONERENDE_KRAFT, NORMALKRAFT, FORSKYDNINGSKRAFT, BOEJNINGSMOMENT, 
	LAENGDE, AREAL, TAU_FORSKYDNINGSSPAENDING, SIGMAN, FORSKYDNINGSPUNKT, INERTIMOMENT, SIGMAB, SIGMA_REF, 
	FLYDESPAENDING, SIKKERHEDSFAKTOR, BREDDE, HOEJDE, DIAMETER, GODSTYKKELSE, PROFIL_TYPE, INDTAST_AREAL;
	
}
