package Logic;

public enum Tilstand {

	VAEGT, PROFIL, VINKEL, TYNGDEKRAFT, DIMENSIONERENDE_KRAFT, NORMALKRAFT, FORSKYDNINGSKRAFT, BOEJNINGSMOMENT, LAENGDE, AREAL, TAU_FORSKYDNINGSSPAENDING,
	SIGMAN;
}
